name = "Simulation of Antwerpen Central south"
description = "Simulation covering the lines from Antwerpen Centraal to St. Katelijne-Waver/Lier"
display_name = "Antwerpen Centraal"
country_code = "BE"
rly_file = "Antwerpen_Centraal.rly"
ttb_files = ["Antwerpen_Centraal_2021.ttb"]
ssn_files = ["Antwerpen_Centraal_2021.ssn"]
year = 2021
factual = true
difficulty = 3
author = "Krizar"
contributors = ["Albert Ball"]